In [2]:
import cv2
import numpy as np
def nearest(img):
    h,w,channels = img.shape
    emptyImage = np.zeros((800,800,channels),np.uint8)
    sh = 800/h
    sw = 800/w
    for i in range(800):
        for j in range(800):
            x = int(i/sh+0.5) #int强制转换，向下取整
            y = int(j/sw+0.5)
            emptyImage[i,j] = img[x,y]
    return emptyImage

In [4]:
img = cv2.imread(r"C:\Users\Administrator\Desktop\lenna.png")
zoom = nearest(img)
print(zoom)
print(zoom.shape)

[[[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 ...

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]]
(800, 800, 3)


In [6]:
cv2.imshow("nearest interp",zoom)
cv2.imshow("image",img)
cv2.waitKey(0)

-1

In [8]:
zoom1 = cv2.resize(img,(800,800),interpolation=cv2.INTER_NEAREST)
print(zoom)

[[[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 ...

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]]


In [10]:
print(zoom.shape)

(800, 800, 3)


In [13]:
cv2.imshow("nearest interp",zoom1)
cv2.imshow("image",img)
cv2.waitKey(0)

-1